In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('features.csv')
print(dataset.shape)

X = dataset.iloc[:, 3:13].values
X=np.delete(X,3,1)
X=np.delete(X,3,1)

for i in range(len(X)):
    if X[i][5]==0:
        X[i][5]=-1
print(X)

print(X[0])
print(X.shape)

y=dataset.iloc[:,2:3].values
print(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 7))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

accuracy= ((cm[0][0]+cm[1][1])/(sum(cm[0])+sum(cm[1])))*100

neuralnetworks_accuracy=accuracy

import pickle
pickle.dump(classifier, open("phishing_model.pkl", 'wb'))


X_test=[1,8,-1,100,1,1,1]
X=np.array(X_test)
X_test=X.reshape(1,-1)

from sklearn import svm
#Assumed you have, X (predictor) and Y (target) for training data set and x_test(predictor) of test_dataset
# Create SVM classification object 
model = svm.SVC(kernel='linear', C=1, gamma=1) 
# there is various option associated with it, like changing kernel, gamma and C value. Will discuss more # about it in next section.Train the model using the training sets and check score
model.fit(X_train, y_train)
model.score(X_train, y_train)
#Predict Output
predicted= model.predict(X_test)
print(predicted)
correct=0
for i in range(len(predicted)):
    if predicted[i]==y_test[i]:
        correct+=1
print("Accuracy=", correct/len(predicted)*100,"%")
svm_acc_linear= correct/len(predicted)*100

model = svm.SVC(kernel='rbf', C=1, gamma=1) 
# there is various option associated with it, like changing kernel, gamma and C value. Will discuss more # about it in next section.Train the model using the training sets and check score
model.fit(X_train, y_train)
model.score(X_train, y_train)
#Predict Output
predicted= model.predict(X_test)

import pickle
pickle.dump(model, open("phishing_model.pkl", 'wb'))

correct=0
for i in range(len(predicted)):
    if predicted[i]==y_test[i]:
        correct+=1
print("Accuracy=", correct/len(predicted)*100,"%")
svm_acc_gaussian= correct/len(predicted)*100

import collections
print(np.count_nonzero(y_test == 1))
print(np.count_nonzero(y_test == 0))

model = svm.SVC(kernel='poly', C=1, gamma=1) 
model.fit(X_train, y_train)
model.score(X_train, y_train)
#Predict Output
predicted= model.predict(X_test)

correct=0
for i in range(len(predicted)):
    if predicted[i]==y_test[i]:
        correct+=1
print("Accuracy=", correct/len(predicted)*100,"%")
svm_acc_poly= correct/len(predicted)*100

from sklearn.metrics import mean_squared_error,r2_score
from sklearn.ensemble import GradientBoostingRegressor
params = {'n_estimators': 500, 'max_depth': 6,
        'learning_rate': 0.05, 'loss': 'huber','alpha':0.95}
clf = GradientBoostingRegressor(**params).fit(X_train, y_train)

y_pred=clf.predict(X_test)
correct=0
for i in range(len(y_pred)):
    if round(y_pred[i])==y_test[i]:
        correct+=1
print("Accuracy=",correct/len(y_pred)*100)
gradient_boosting_accuracy=(correct/len(y_pred))*100

print(neuralnetworks_accuracy,svm_acc_linear,svm_acc_gaussian,svm_acc_poly,gradient_boosting_accuracy)

plt.bar(0, svm_acc_gaussian, width=0.5, bottom=None, align='edge', data=None,label="SVM Gaussian")
plt.bar(1, svm_acc_linear, width=0.5, bottom=None, align='edge', data=None,label="SVM Linear")
plt.bar(2, neuralnetworks_accuracy, width=0.5, bottom=None, align='edge', data=None,label="Neural Network")
plt.bar(3, svm_acc_poly, width=0.5, bottom=None, align='edge', data=None,label="SVM Poly")
plt.bar(4, gradient_boosting_accuracy, width=0.5, bottom=None, align='edge', data=None,label="Gradient Boosting")
plt.legend()
plt.xlabel("Plots are in increasing order");
plt.ylabel("Percentage")

abc=[]
defe=[]
for i in range(len(X)):
    if X[i][5]==1:
        abc.append(i)
    else:
        defe.append(i)
plt.plot(abc)
plt.show()

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
predicted=model.predict(X_test)
import pickle
pickle.dump(model, open("phishing_model.pkl", 'wb'))

(5097, 12)
[[1 6 -1 ... 0.0 -1 -1]
 [1 7 -1 ... 0.95 -1 1]
 [1 8 -1 ... 0.78 -1 -1]
 ...
 [-1 13 -1 ... 0.0 -1 0]
 [-1 13 -1 ... 0.95 -1 -1]
 [1 7 -1 ... 0.95 -1 -1]]
[1 6 -1 5 0.0 -1 -1]
(5097, 7)
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [1]]


/Users/hariharakumarrajanala/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/hariharakumarrajanala/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/Users/hariharakumarrajanala/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:38: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=7, units=6, kernel_initializer="uniform")`
/Users/hariharakumarrajanala/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:40: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="re

Epoch 1/100
4077/4077 [==============================] - 3s 723us/step - loss: 0.6909 - acc: 0.5440
Epoch 2/100
4077/4077 [==============================] - 1s 325us/step - loss: 0.6892 - acc: 0.5465
Epoch 3/100
4077/4077 [==============================] - 1s 322us/step - loss: 0.2985 - acc: 0.8219
Epoch 4/100
4077/4077 [==============================] - 1s 325us/step - loss: 0.0692 - acc: 0.9843
Epoch 5/100
4077/4077 [==============================] - 1s 329us/step - loss: 0.0690 - acc: 0.9843
Epoch 6/100
4077/4077 [==============================] - 1s 327us/step - loss: 0.0696 - acc: 0.9841
Epoch 7/100
4077/4077 [==============================] - 1s 328us/step - loss: 0.0683 - acc: 0.9843
Epoch 8/100
4077/4077 [==============================] - 1s 347us/step - loss: 0.0689 - acc: 0.9838
Epoch 9/100
4077/4077 [==============================] - 1s 333us/step - loss: 0.0683 - acc: 0.9843
Epoch 10/100
4077/4077 [==============================] - 1s 346us/step - loss: 0.0685 - acc: 0.9841

4077/4077 [==============================] - 1s 329us/step - loss: 0.0678 - acc: 0.9845
Epoch 82/100
4077/4077 [==============================] - 1s 329us/step - loss: 0.0678 - acc: 0.9845
Epoch 83/100
4077/4077 [==============================] - 1s 327us/step - loss: 0.0678 - acc: 0.9845
Epoch 84/100
4077/4077 [==============================] - 1s 330us/step - loss: 0.0680 - acc: 0.9843 0s - loss: 0.0654 -
Epoch 85/100
4077/4077 [==============================] - 1s 333us/step - loss: 0.0681 - acc: 0.9845
Epoch 86/100
4077/4077 [==============================] - 1s 328us/step - loss: 0.0679 - acc: 0.9845
Epoch 87/100
4077/4077 [==============================] - 1s 329us/step - loss: 0.0679 - acc: 0.9845
Epoch 88/100
4077/4077 [==============================] - 1s 330us/step - loss: 0.0679 - acc: 0.9845
Epoch 89/100
4077/4077 [==============================] - 1s 329us/step - loss: 0.0681 - acc: 0.9843
Epoch 90/100
4077/4077 [==============================] - 1s 328us/step - loss: 0.06

/Users/hariharakumarrajanala/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[1]
Accuracy= 0.0 %
Accuracy= 100.0 %
443
577
Accuracy= 0.0 %
Accuracy= 100.0
97.94117647058823 0.0 100.0 0.0 100.0


IndexError: invalid index to scalar variable.